apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: core
spec:
  containers:
  - name: debug
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /mnt
      name: rabbitmq-storage
  volumes:
  - name: rabbitmq-storage
    persistentVolumeClaim:
      claimName: rabbit-pvc
  restartPolicy: Never
