# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("etcd.proto", :syntax => :proto3) do
    add_message "dynamos.EtcdKey" do
      optional :path, :string, 1
    end
    add_message "dynamos.Dataset" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :delimiter, :string, 3
      repeated :tables, :string, 4
    end
  end
end

module Dynamos
  EtcdKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.EtcdKey").msgclass
  Dataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.Dataset").msgclass
end
