# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("generic.proto", :syntax => :proto3) do
    add_message "dynamos.RequestMetadata" do
      optional :correlation_id, :string, 1
      optional :destination_queue, :string, 2
      optional :job_name, :string, 3
      optional :return_address, :string, 4
      optional :job_id, :string, 5
    end
    add_message "dynamos.ServiceName" do
      optional :service_name, :string, 1
    end
  end
end

module Dynamos
  RequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.RequestMetadata").msgclass
  ServiceName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.ServiceName").msgclass
end
