# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("health.proto", :syntax => :proto3) do
    add_message "dynamos.HealthCheckRequest" do
      optional :service, :string, 1
    end
    add_message "dynamos.HealthCheckResponse" do
      optional :status, :enum, 1, "dynamos.HealthCheckResponse.ServingStatus"
    end
    add_enum "dynamos.HealthCheckResponse.ServingStatus" do
      value :UNKNOWN, 0
      value :SERVING, 1
      value :NOT_SERVING, 2
      value :SERVICE_UNKNOWN, 3
    end
  end
end

module Dynamos
  HealthCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.HealthCheckRequest").msgclass
  HealthCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.HealthCheckResponse").msgclass
  HealthCheckResponse::ServingStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.HealthCheckResponse.ServingStatus").enummodule
end
