# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microserviceCommunication.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'google/protobuf/any_pb'
require 'generic_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("microserviceCommunication.proto", :syntax => :proto3) do
    add_message "dynamos.MicroserviceCommunication" do
      optional :type, :string, 1
      optional :request_type, :string, 2
      optional :data, :message, 3, "google.protobuf.Struct"
      map :metadata, :string, :string, 4
      optional :original_request, :message, 5, "google.protobuf.Any"
      optional :request_metadata, :message, 6, "dynamos.RequestMetadata"
      map :traces, :string, :bytes, 7
      optional :result, :bytes, 8
      repeated :routing_data, :string, 9
    end
    add_message "dynamos.ContinueReceiving" do
      optional :continue_receiving, :bool, 1
    end
  end
end

module Dynamos
  MicroserviceCommunication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.MicroserviceCommunication").msgclass
  ContinueReceiving = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dynamos.ContinueReceiving").msgclass
end
